### PR TITLE
Mobile/fix-searchbar-close

### PR DESCRIPTION
**Pull request by muhammetssen**

### CODE REVIEW

**Comment by salimtirit** [comment]
I tried your code.  I didn't like the idea of having an arrow inside the search bar for this purpose. I think the user should be able to use the built-in go-back functionality of their phone. So I am not merging this.  If this is not possible or really hard to implement can you please center the arrow and the text 
image

**Comment by muhammetssen** [comment]
Unfortunately, using the native go back functionalities is not trivial. I searched for a way that does not require changing the main navigation structure; however, could not find one that works with `persistent_bottom_nav_bar`. 

As you said, I centered the arrow and text 
image

**Comment by salimtirit** [comment]
Thank you for your efforts. Good job!

**Review by salimtirit — COMMENTED** [review]
Thank you for your efforts. Good job!

**Pull request merged**
