### PR TITLE
populate only references and remove unnecessary fields from returns of enrollment and course functions

### PR DESCRIPTION
**Pull request by furkanakkurt1335**
This PR is for removing non-reference fields from populates, not urgent.

### CODE REVIEW

**Review by ersoykadir — CHANGES_REQUESTED** [review]
- Can you please make a check on create enrollment, whether given course_id exists in our db or not. 
- Can you please add a regex search on getEnrolledCourses just like getCourses endpoint

**Comment by furkanakkurt1335** [comment]
Create enrollment can be done in another PR but currently you shouldn't be able to create an enrollment without an existing course because the enrollment schema has a course reference.

Regarding the second getEnrolledCourses change, I remember front-end requesting it. This PR does not relate to that. Let's do that in another PR.

**Comment by ersoykadir** [comment]
Okay, requested changes will be done on another PR.

**Review by ersoykadir — APPROVED** [review]
LGTM

**Pull request merged**
