### PR TITLE
start db creation script

### PR DESCRIPTION
**Pull request by furkanakkurt1335**
We need a _mongosh_ script for mock data creation written in JavaScript.

You can run the script in the `util` folder by: `mongosh --file create.js`, after configuring the database connection at the start of the file.

Fields are currently empty, we can start adding mock data in this file.

I added all the schema fields. I changed some ID fields to reference fields, we may make them so in the schemas also.

### CODE REVIEW

**Comment by furkanakkurt1335** [comment]
Related issue: #349

**Review by yilmaz-burak — COMMENTED** [review]
Thanks for the effort, but I am not sure whether this should be how we populate the database...
We should use env variables, for one, so that we can quickly run this to populate any db.
And also, we should create objects from these, so that we don't have to manually enter some ids.
Let's wait to get some data collected in Notion, then we can have a look at this again.

**Comment by furkanakkurt1335** [comment]
JavaScript mongosh scripts return IDs after insertion. This looks very programmatic to me. Mock data that'll be gathered on Notion can be converted to the script form.

Re: env, we can modify as such. As we talked about in the meeting, the actual work is creating mock content. Hopefully, we'll do that as a group rather fast.

**Comment by ersoykadir** [comment]
This can stay as a draft on repo. We can do the necessary changes later on.

**Pull request merged**
