### PR TITLE
Mobile: login and registration

### PR DESCRIPTION
**Pull request by bilalcim**
Closes #307. Everything there is also here.

What already existed in #307:

- Input fields for login and registration forms.
- The design of login and registration pages.
- Redirections within the mobile app.
- Input validation.

What is new:

- Backend connection for login and registration pages.
- Initializing the app to the login page.
- Login and registration pop-ups.
- Agreement to the "Terms of Use and Privacy Policy."

As it stands, this branch has no conflicts. It can be merged directly after review. The reviewer is @muhammetssen, taking on from #307.

### CODE REVIEW

**Comment by muhammetssen** [comment]
Hi, we should not show the login page every time a user opens the app. Instead of directing to the loginView in main.dart, you can direct to introView, like before, and check if user is able to refresh their token. In order to do that, you can create a function in userService to check if there exists a token in the PersistenceService.

**Review by muhammetssen — CHANGES_REQUESTED** [review]
Hi, we should not show the login page every time a user opens the app. Instead of directing to the loginView in main.dart, you can direct to introView, like before, and check if user is able to refresh their token. In order to do that, you can create a function in userService to check if there exists a token in the PersistenceService.

**Comment by bilalcim** [comment]
Does this work?

(We need to add a log-out button somewhere :) )

**Comment by muhammetssen** [comment]
You can add the logout button to profile page's right top corner.

Cannot seem to register 
image

**Review by muhammetssen — APPROVED** [review]
Thanks!!

**Pull request merged**
