### PR TITLE
[Mobile] Event

### LINKED ISSUE #419: [Mobile] Events
### Issue

As per our arrangements for the next milestone, Milestone 2, I will design the event section of a course.

There are a couple of pages here:

1. **The event creation form:** The design will follow that of Scenario 1 as much as possible, which you can see below:
<p align="center">
Screen Shot 2022-12-04 at 16 24 45
</p>

2. **The event section of a course:** There will be a button directing to the creation page, followed by the events already set. These prior events will direct the user to page 3.

3. **Details page:** Learners will be able to see the details of the event. If a learner is the organizer of the event, then they will see an "Edit" button directing to page 4.

4. E**dit page:** Similar to the event creation page, only with fields already filled.

### Task(s)

- [x] Design Page 1.
- [x] Design Page 2.
- [x] Design Page 3.
- [ ] Design Page 4.

### Deliverable(s)

* A pull request  from the ``mobile/event`` branch.

### Acceptance Criteria

* A learner can set up an event.
* A learner can see the prior events in a specific course.
* A learner can see the details of an event.
* An organizer can edit the details of their event.

### Deadline of the issue

06.12.2022

### Reviewer

None

### Deadline for Review

TBD

### PR DESCRIPTION
**Pull request by bilalcim**
Closes #419. This pull request brings features of the event creation mentioned in #419:

- Created the Event model and serializers.
- Designed the pages specified in #419, except for 4.
- Connected these to the backend.

### CODE REVIEW

**Review by salimtirit — CHANGES_REQUESTED** [review]
I have solved conflicts with the main branch and made some improvements for both the visual part and its functionality of it.

But still I would like to recommend some changes:
 - I think the user should be able to hit the create button if they entered the necessary information which should be shown with the '*' symbol. And if they did not enter the necessary information there should be a notification stating "You should enter all necessary info". Quota and end date are not necessary for the backend I made the change in the definition of the event but in the form part, it should not be checked. 
 - The user should not be able to enter a date that does not make sense which is before today and maybe after 1 year it should be more restricted.
 - The user should not be able to enter the end date before the start date, this is not checked in the backend I will also inform them of this situation but we should check this also
 - Selecting event location (or at least giving coordinates) should be implemented
 - Seeing the event location should be implemented 
 
If you can implement all of these features it will be fantastic. But if it is not possible please inform me I will try to help you with it.

**Comment by bilalcim** [comment]
I have tried to address your issues other than the location. Can you take a look?

**Comment by salimtirit** [comment]
I have added a button to show the event location on the phone's map application. (google maps etc.). The selecting event location part is more tricky. I did some research but I couldn't find an easy way to implement it so I guess we can give longitude and latitude input as numbers.

**Comment by salimtirit** [comment]
I also added longitude & latitude input as double. If this is convenient we can keep it as it is but it would be better if you check out [flutter_osm_plugin](https://pub.dev/packages/flutter_osm_plugin) and implement selecting the location from the map it will be better [map_location_picker](https://pub.dev/packages/map_location_picker) works with google maps so u will need an API key for google maps. I wouldn't use it if I were u.

**Comment by bilalcim** [comment]
I have added participation and unparticipation. Small visual improvements will come soon.

**Comment by bilalcim** [comment]
Visual improvements have been made to participate/unparticipate. Waiting for review...

**Comment by salimtirit** [comment]
LGTM!

**Comment by salimtirit** [comment]
Forgot to merge sorry

**Pull request merged**
