### PR TITLE
Mobile/markdown editor

### LINKED ISSUE #375: [Mobile] Creating Markdown Editor Widget
### Issue

We need a component that can be used at every part of Bucademy app. We shall support markdown language in comments, discussions, resources, notes etc. Hence, we can use the same input component for all of those.

### Task(s)

- [ ] Finding a markdown package from [pub.dev](pub.dev)
- [ ] Exploring different use cases of the package
- [ ] Creating a component that should include
  - [ ] OnChange callbacks
  - [ ] Loading state variables
  - [ ] OnComplete callbacks

### Deliverable(s)

- MarkdownInput widget

### Acceptance Criteria

- Component shall be responsive to the screen size
- Component shall be easy to use at other pages
- Component shall support providing onChange and onComplete callbacks
- Component shall support providing a loading state to indicate user during loadings

### Deadline of the issue

25.11.2022 23:59

### Reviewer

_No response_

### Deadline for Review

_No response_

### PR DESCRIPTION
**Pull request by muhammetssen**
Closes #375
- Installed `markdown_editable_textinput` package
- Created a component to handle inputs and loading states
markdowngif

### CODE REVIEW

**Comment by hsuleerkul** [comment]
Hi! Could you share an example call of **markdownInput** component? 
I couldn't try the widget because I couldn't figure out how I can create one :( 
Other than that, the code looks useful and we can merge it after I try the new component. :) 
Thank you!

**Comment by muhammetssen** [comment]
Hi, you can check the usage [here](https://github.com/bounswe/bounswe2022group3/blob/9ca513504e7fe5dfae7b3b52eb8b8c4fe489579d/app/mobile/lib/view/course/discussion/discussion_view.dart#L35)

**Comment by hsuleerkul** [comment]
I tested the widget and it works well. Thank you!

**Review by hsuleerkul — APPROVED** [review]
Thanks!

**Pull request merged**
